<?php 
$form = $this->form;
$form->prepare();
?>
<?=$this->form()->openTag($form)?>
	<div class="page-head">
	    <h2 class="m-b-less">
	        Observation Guide
	    </h2>
	</div>
    
    <?php foreach($form as $fieldset) : ?>
    <div class="row">
    	<div class="col-xs-12">
        <section class="panel">
        	<header class="panel-heading">
            	<?=$fieldset->getLabel()?>
            </header>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-xs-12">
                    <?php foreach($fieldset as $element) : ?>\
                        <!-- DEFAULT -->
                    	<?=$this->formRow($element)?>
                        <!-- END DEFAULT -->
                    <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </section>
    </div>
    </div>
    <?php endforeach; ?>
  
	<div class="row">
		<div class="col-xs-12">
		<button class="btn btn-info btn-block" type="submit">Submit</button>
		</div>
	</div>

<?php echo $this->form()->closeTag()?>