<?php

$this->headScript()->prependFile($this->basePath() . '/assets/admin/js/jquery-ui.js');
$this->inlineScript()->prependFile($this->basePath() . '/assets/admin/js/plugins/ckeditor/adapters/jquery.js');
$this->inlineScript()->prependFile($this->basePath() . '/assets/admin/js/plugins/ckeditor/config.js');
$this->inlineScript()->prependFile($this->basePath() . '/assets/admin/js/plugins/ckeditor/ckeditor.js');

$form->setAttribute('action', $this->url('admin/form', array('action' => 'create-section', 'id' => $this->id)))
	 ->prepare();

$fields = $form->get('form-fieldset');
$element = $fields->get('element');
?>

<div class="page-head">
    <h3 class="m-b-less">
        Create Section/Fieldset
    </h3>
</div>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formRow($fields->get('class')); ?>
<div class="wrapper">
	<div class="row">
		<div class="col-xs-12">
            <section class="panel">
                <div class="panel-body">
                    <div class="form-group">
                        <label for="">Section Name</label>
                        <?php echo $this->formRow($fields->get('name')); ?>
                    </div>
                    <div class="form-group">
                        <label for="">Section Label</label>
                        <?php echo $this->formRow($fields->get('label')); ?>
                    </div>
                    <div class="form-group">
                        <label for="">Sort</label><br />
                        <?php echo $this->formRow($fields->get('sort')); ?>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label><br />
                        <?php echo $this->formRow($fields->get('description')); ?>
                    </div>
                </div>
            </section>
		</div>
	</div>
    <div class="row">
        <div class="col-xs-12">
            <section class="panel">
                <header class="panel-heading head-border">
                    Elements
                </header>
                <table class="table table-elements" >
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Label</th>
                        <th>Class</th>
                        <th>Options</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($element as $k=>$elm) { ?>

                    <tr>
                        <td><?php echo $this->formRow($elm->get('name')); ?></td>
                        <td><?php echo $this->formRow($elm->get('label')); ?></td>
                        <td><?php echo $this->formRow($elm->get('class')); ?></td>
                        <td>
                            <?php echo $this->formRow($elm->get('options')); ?>
                            <textarea class="value-options form-control" name="value-options"></textarea>
                            <small>Note: <em>One item per line</em></small>
                            <br /><br />
                            <strong>Attributes</strong>
                            <?php echo $this->formRow($elm->get('attributes')); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </section>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <section class="panel">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </section>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<script type="text/javascript">
    $(document).ready(function(){
        $('textarea[name="form-fieldset[description]"]').ckeditor();
    });
</script>