<?php
$fields = $form->get('form');
$form
 ->setAttribute('action', $this->url('admin/form', array('action' => 'create-form')))
 ->prepare()
;
?>

<div class="page-head">
    <h3 class="m-b-less">
        Create Form
    </h3>
</div>

<div class="wrapper">
	<div class="row">
		<div class="col-xs-12">
            <section class="panel">
                <?php echo $this->form()->openTag($form); ?>
                <div class="panel-body">

                    <?=$this->flashMessenger()
                            ->setMessageOpenFormat('<div%s><h4>Error</h4><button data-dismiss="alert" class="close close-sm" type="button"><i class="fa fa-times"></i></button><p>')
                            ->setMessageSeparatorString('</p><p>')
                            ->setMessageCloseString('</p></div>')
                            ->render('error', array('alert', 'alert-block', 'alert-danger', 'fade', 'in'))?>

                    <div class="form-group">
                        <label for="">Form Name</label>
                        <?php echo $this->formRow($fields->get('name')); ?>
                    </div>   
                    <div class="form-group">
                        <label for="">Form Label</label>
                        <?php echo $this->formRow($fields->get('label')); ?>
                    </div>
                    <div class="form-group">
                        <label for="">RedirectToPage</label>
                        <?php echo $this->formRow($fields->get('redirect')); ?>
                    </div>
                </div>
				<?php 
				echo $this->formSubmit($form->get('submit'));
				echo $this->form()->closeTag();
				?>
            </section>
		</div>
	</div>
</div>

